# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategorieZakupu',
            fields=[
                ('nazwa', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('czy_opcjonalny', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'kategorie_zakupu',
            },
        ),
        migrations.CreateModel(
            name='Paragony',
            fields=[
                ('czas_zakupu', models.DateField()),
                ('id', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'paragony',
            },
        ),
        migrations.CreateModel(
            name='SieciSklepow',
            fields=[
                ('nazwa', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'sieci_sklepow',
            },
        ),
        migrations.CreateModel(
            name='Sklepy',
            fields=[
                ('adres', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'sklepy',
            },
        ),
        migrations.CreateModel(
            name='Zakupy',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('nazwa_produktu', models.CharField(max_length=30)),
                ('cena_jednostkowa', models.FloatField()),
                ('ilosc_produktu', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'zakupy',
            },
        ),
    ]
