# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_budget', '0002_auto_20170209_0015_squashed_0004_auto_20170213_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.ProductCategory'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
