# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_budget', '0003_auto_20170213_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='brand',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.Shop'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
