# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_budget', '0003_auto_20170213_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='unit_price_currency',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
