# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_budget', '0004_auto_20170214_1117'),
    ]

    operations = [
    ]
